# Generated by Django 3.1.3 on 2020-11-27 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('cat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('contact_info', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('d_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('vehicle_info', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('v_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_name', models.CharField(max_length=40)),
                ('product_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('v_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_name', models.CharField(max_length=40)),
                ('cuisine', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreBranch',
            fields=[
                ('g_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('g_location', models.CharField(max_length=100, unique=True)),
                ('g_phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('v', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms.grocerystore')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantBranch',
            fields=[
                ('r_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('r_location', models.CharField(max_length=100, unique=True)),
                ('r_phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('v', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('m_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=10)),
                ('r', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms.restaurantbranch')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('f_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms.menu')),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='g',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms.storebranch'),
        ),
        migrations.CreateModel(
            name='C_Order',
            fields=[
                ('o_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('o_type', models.CharField(blank=True, default='DELIVERY', max_length=8, null=True)),
                ('o_date', models.DateField(blank=True, null=True)),
                ('c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms.customer')),
                ('d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms.driver')),
                ('f_name', models.ForeignKey(blank=True, db_column='f_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms.food')),
                ('p_name', models.ForeignKey(blank=True, db_column='p_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms.product')),
            ],
        ),
    ]
