# Generated by Django 3.1.3 on 2020-11-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COrder',
            fields=[
                ('o_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('o_type', models.CharField(blank=True, max_length=8, null=True)),
                ('o_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'c_order',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grocerystore',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='restaurantbranch',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='storebranch',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='C_Order',
        ),
    ]
