# Generated by Django 3.1.3 on 2020-11-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0002_auto_20201127_1509'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalog',
            table='catalog',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='driver',
            table='driver',
        ),
        migrations.AlterModelTable(
            name='food',
            table='food',
        ),
        migrations.AlterModelTable(
            name='grocerystore',
            table='grocery_store',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
        migrations.AlterModelTable(
            name='restaurantbranch',
            table='restaurant_branch',
        ),
        migrations.AlterModelTable(
            name='storebranch',
            table='store_branch',
        ),
    ]
