# Generated by Django 3.1.3 on 2020-11-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0003_auto_20201127_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='g',
        ),
        migrations.DeleteModel(
            name='COrder',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.RemoveField(
            model_name='food',
            name='m',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='r',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='restaurantbranch',
            name='v',
        ),
        migrations.RemoveField(
            model_name='storebranch',
            name='v',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='GroceryStore',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='RestaurantBranch',
        ),
        migrations.DeleteModel(
            name='StoreBranch',
        ),
    ]
