# Generated by Django 3.1.3 on 2020-11-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbms', '0004_auto_20201127_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('cat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='COrder',
            fields=[
                ('o_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('o_type', models.CharField(blank=True, max_length=8, null=True)),
                ('o_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'c_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('contact_info', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('d_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('vehicle_info', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('f_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('v_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_name', models.CharField(max_length=40)),
                ('product_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'grocery_store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('m_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('v_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_name', models.CharField(max_length=40)),
                ('cuisine', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantBranch',
            fields=[
                ('r_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('r_location', models.CharField(max_length=100)),
                ('r_phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'restaurant_branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreBranch',
            fields=[
                ('g_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('g_location', models.CharField(max_length=100)),
                ('g_phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'store_branch',
                'managed': False,
            },
        ),
    ]
