CREATE TABLE CUSTOMER_2 (CONTACT_INFO  VARCHAR2 (30) PRIMARY KEY,C_NAME VARCHAR2 (20) NOT NULL);

CREATE TABLE CUSTOMER_1 (C_ID INTEGER PRIMARY KEY,ADDRESS VARCHAR2 (30) NOT NULL,CONTACT_INFO  VARCHAR2 (30), FOREIGN KEY (CONTACT_INFO) REFERENCES CUSTOMER_2 (CONTACT_INFO));


CREATE TABLE DRIVER (D_ID INTEGER PRIMARY KEY,D_NAME VARCHAR2 (20) NOT NULL,RATING NUMBER(2,1),VEHICLE_INFO VARCHAR2 (25) NOT NULL UNIQUE);

CREATE TABLE RESTAURANT_2 (	V_NAME VARCHAR2 (40) PRIMARY KEY,	CUISINE VARCHAR2 (20));

CREATE TABLE RESTAURANT_1 (	V_ID INTEGER PRIMARY KEY, V_NAME VARCHAR2 (40),FOREIGN KEY(V_NAME) REFERENCES RESTAURANT_2 (V_NAME));

CREATE TABLE GROCERY_STORE_2(V_NAME VARCHAR2 (40) PRIMARY KEY,PRODUCT_TYPE VARCHAR2 (20));

CREATE TABLE GROCERY_STORE_1(V_ID INTEGER PRIMARY KEY,	V_NAME VARCHAR2 (40),FOREIGN KEY(V_NAME) REFERENCES GROCERY_STORE_2 (V_NAME));


CREATE TABLE STORE_BRANCH(G_ID INTEGER PRIMARY KEY, G_LOCATION VARCHAR2 (100) NOT NULL , G_PHONE VARCHAR (20) UNIQUE,V_ID INTEGER REFERENCES GROCERY_STORE_1(V_ID));

CREATE TABLE RESTAURANT_BRANCH(R_ID INTEGER PRIMARY KEY,R_LOCATION VARCHAR2 (100) NOT NULL ,R_PHONE VARCHAR2 (20) UNIQUE,V_ID INTEGER REFERENCES RESTAURANT_1 (V_ID));

CREATE TABLE MENU(M_ID INTEGER  PRIMARY KEY,CAT VARCHAR2 (10) NOT NULL,R_ID INTEGER REFERENCES RESTAURANT_BRANCH (R_ID));

CREATE TABLE CATALOG(CAT_ID INTEGER PRIMARY KEY, CAT VARCHAR2 (15) NOT NULL, G_ID INTEGER REFERENCES STORE_BRANCH (G_ID));

CREATE TABLE FOOD(F_NAME VARCHAR2 (15) PRIMARY KEY, PRICE NUMBER(5,2) NOT NULL, QUANTITY INTEGER NOT NULL, DESCRIPTION VARCHAR2 (150), M_ID INTEGER REFERENCES MENU (M_ID));

CREATE TABLE PRODUCT(P_NAME  VARCHAR2 (15) PRIMARY KEY, PRICE NUMBER(5,2) NOT NULL, QUANTITY INTEGER NOT NULL, DESCRIPTION VARCHAR2 (150),CAT_ID INTEGER REFERENCES CATALOG (CAT_ID));

CREATE TABLE C_ORDER(O_ID INTEGER PRIMARY KEY,O_TYPE VARCHAR2(8) DEFAULT 'DELIVERY',O_DATE DATE,P_NAME VARCHAR2 (15),FOREIGN KEY(P_NAME) REFERENCES PRODUCT (P_NAME),F_NAME VARCHAR2 (15) ,FOREIGN KEY(F_NAME) REFERENCES FOOD(F_NAME),C_ID INTEGER,FOREIGN KEY(C_ID) REFERENCES CUSTOMER_1 (C_ID), D_ID INTEGER,FOREIGN KEY(D_ID) REFERENCES DRIVER (D_ID));